kind: Deployment
apiVersion: apps/v1
metadata:
  name: mongodb-deployment
  namespace: chat-app
spec:
  replicas: 1  # no of pods/replicas
  selector:     # to match labels
    matchLabels:
      app: mongodb # label must match this

  # pod.yml config
  template:
    metadata:
      name: mongodb-pod
      labels: # add labels
        app: mongodb
    spec:
      containers:
        - name: chatapp-mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: mongoadmin
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: secret

          volumeMounts:
            - mountPath: /var/www/html
              name: mongo-data
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongodb-pvc

