kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongodb-pv
  namespace: chat-app
  labels:
    app: mongodb

spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain # retain evenif pv got deleted
  storageClassName: local-storage
  hostPath:
    path: /data
