kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-deployment
  namespace: nginx
spec:
  replicas: 3   # no of pods/replicas
  selector:     # to match labels
    matchLabels:
      app: nginx # label must match this

  # pod.yml config
  template:
    metadata:
      name: nginx-deployment-pod
      labels: # add labels
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /var/www/html
              name: my-volume
      volumes:
        - name: my-volume
          persistentVolumeClaim:
            claimName: local-pvc
  
