kind: Deployment
apiVersion: apps/v1
metadata:
  name: apache-deployment
  namespace: apache
spec:
  replicas: 1   # no of pods/replicas
  selector:     # to match labels
    matchLabels:
      app: apache # label must match this

  # pod.yml config
  template:
    metadata:
      name: apache-deployment-pod
      labels: # add labels
        app: apache
    spec:
      containers:
        - name: apache
          image: httpd:latest
          ports:
            - containerPort: 80
          #Limit and resources: [min-max]
          resources:
            requests:
              cpu: 100m  #The HPA will now scale if usage hits 5m (5% of 100m)
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi



